### ISSUE TITLE
Vulnerable default versions of the python runtime

### ISSUE THREAD

**Issue by desgovedarska** [cloudfoundry/python-buildpack#113]
Hi,
I have a question/suggestion. :)
We perform a weekly security scan on the open source components we use in our project and we noticed that the current default version of the python runtime in the buildpack (2.7.14) has one high-risk security vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2018-1000030) and two medium ones (https://nvd.nist.gov/vuln/detail/CVE-2016-1494 and https://nvd.nist.gov/vuln/detail/CVE-2010-3492) thus it would be a good idea to change it. Furthermore I was wondering why the default is still python 2.x since as we all know, support for that will soon cease. Shouldn't we switch to having python 3.x as default or there are too many (what?) objections to that?

Thanks & regards,
Dessie

**Comment by sclevine** [comment]
Hi @desgovedarska,

Thanks for pointing this out -- 2.7.15 is available in the buildpack, but it looks like the default version was hard-coded to `2.7.14`, instead of set to `2.7.x`. We'll fix this and cut a release ASAP. In the meantime, you could lock to `2.7.15`. 

Python 2.7 will continue to be supported for at least 1.5 years. Changing the default version would be breaking change, but we agree that it should happen well before 2.7 hits EOL.

**Comment by sclevine** [comment]
Should be fixed in v1.6.18.

**Comment by cclauss** [comment]
234 days until Python 2 end of life.
