### ISSUE TITLE
No support for Python 3.4.3

### ISSUE THREAD

**Issue by cclauss** [cloudfoundry/python-buildpack#15]
[Python 3.4.3](https://www.python.org/downloads/release/python-343/) was released on February 25th, 2015.

**Comment by flavorjones** [comment]
We will soon be releasing updates to all the buildpacks with current versions of interpreters. This will likely coincide with the "skinny buildpacks" track of work that you can see here:

> https://www.pivotaltracker.com/epic/show/1747328

because the buildpacks as a group are quite large and unwieldy at this point.

Thanks for your patience, and thank you for using Cloud Foundry!

**Comment by flavorjones** [comment]
This will actually be worked on under the auspices of this story:

> https://www.pivotaltracker.com/story/show/90697224

**Comment by crawsible** [comment]
@cclauss: We now have support for python 3.4.3 on our ["skinny" feature branch](https://github.com/cloudfoundry/python-buildpack/tree/skinny), and it will be included in the next release cut for the Python buildpack.

Thanks for using Cloud Foundry!
