### ISSUE TITLE
Could not install python: no match found for 3.7.4 in [ ... ]

### ISSUE THREAD

**Issue by jason-upchurch** [cloudfoundry/python-buildpack#158]
Question: why is python 3.7.4 no longer available? (what is the general policy for which versions are available?). How does one target a specific version of python, e.g., 3.7.4 rather than getting just the latest version of 3.7 by using 3.7.x?

Error:

```
-----> Python Buildpack version 1.7.5
-----> Supplying Python
       **ERROR** Could not install python: no match found for 3.7.4 in [2.7.16 2.7.17 3.5.7 3.5.9 3.6.9 3.6.10 3.7.5 3.7.6 3.8.0 3.8.1]
```

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
`cf version 6.43.0+815ea2f3d.2019-02-20`

What version of the buildpack you are using?
`1.75`

If you were attempting to accomplish a task, what was it you were attempting to do?
build

What did you expect to happen?
successful build

What was the actual behavior?
unsuccessful build (python version not found)

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ryanmoran** [comment]
Hey @jason-upchurch!

Python 3.7.4 is no longer available because the buildpack only supports the 2 latest patch versions of each version line (2.7, 3.5, 3.6, 3.7, 3.8). At the time of the release of the v1.7.5 buildpack, those versions were 3.7.5 and 3.7.6. The [release notes](https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.5) indicate that version 3.7.4 was removed in this version of the buildpack.

As the buildpack regularly removes old patch versions of each line, the only method for pinning to a specific patch version is to keep up with the buildpack by checking out the release notes and updating your version to match what versions are available.
