### ISSUE TITLE
CONDA_SSL_VERIFY env not getting picked up from manifest for private conda repo

### ISSUE THREAD

**Issue by dilu24x7** [cloudfoundry/python-buildpack#252]
I am trying to configure private conda repo using this link https://docs.cloudfoundry.org/buildpacks/python/index.html#private-repos-conda and i tried providing CONDA_SSL_VERIFY to cert path within ENV in manifest.yml also CONDA_SSL_VERIFY: false, but in both cases its getting ignored. I think the conda config should be set upfront considering this ENV value like;

conda config --set ssl_verify <pathToYourFile>.crt

or a -k option [here](https://github.com/cloudfoundry/python-buildpack/blob/c58ffbaca3107862bf5fb19154e2ccd536057d45/src/python/conda/conda.go#L125) considering CONDA_SSL_VERIFY: false

**Comment by thitch97** [comment]
Hi @dilu24x7, thanks for your feedback. We'd like to investigate this issue further. Would you be able to provide the log output/errors you noticed while trying to configure your app and any relevant source code so that we can attempt to reproduce the error? Please also include the versions of CF and the `python-buildpack` that you are using.

**Comment by menehune23** [comment]
Hi @dilu24x7, closing this issue as stale. Please feel free to reopen with detailed reproduction steps if you'd like further help with this.
