### ISSUE TITLE
Current releases not supported: Python 2.7.11, Python 3.5.1, Pypy 4.0.1

### ISSUE THREAD

**Issue by cclauss** [cloudfoundry/python-buildpack#30]

**Comment by Dannyzen** [comment]
Hey @cclauss have you tried the [newest](https://github.com/cloudfoundry/python-buildpack/releases) buildpack?

**Comment by cclauss** [comment]
Ahhh...  Now I understand that this project uses https://github.com/cloudfoundry/python-buildpack/blob/master/manifest.yml instead of the build/runtimes files used in upstream.

__What is the stance on http://pypy.org support in this buildpack?__

**Comment by jtarchie** [comment]
@cclauss we try to keep the buildpacks size small because the binaries are packaged with the buildpack, to support disconnected (firewall) environments. PyPy appears to be the least used of the Pythons. If you can provide any usage statistics or killer feature requirement, we could open the discussion.

**Comment by cclauss** [comment]
Pypy 4.0.1 runs Python code an average of __7 times faster__ than CPython 2.7.  http://pypy.org/features.html
