### ISSUE TITLE
Document what version of glibc python-buildpack uses

### ISSUE THREAD

**Issue by vanschelven** [cloudfoundry/python-buildpack#612]
AFAICT the glibc version that python-buildpack uses is currently undocumented.

This matters, because the glibc version determines which "many linux" wheels can be used when vendoring wheels. E.g. for the current version of cryptography multiple manylinux wheels are available, but not all of them will be useable in a current python-buildpack:

* cryptography-38.0.1-pp39-pypy39_pp73-manylinux_2_28_x86_64.whl 
* cryptography-38.0.1-pp39-pypy39_pp73-manylinux_2_24_x86_64.whl 
* cryptography-38.0.1-pp39-pypy39_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

**Comment by vanschelven** [comment]
> `libc` is provided as part of the stack, not the python buildpack.

I'm not quite sure what that means for me as the user of any given buildpack though... where do the various parts of this "stack" get assembled? And if I were to e.g think that the `glibc` was outdated and should be upgraded to be of practical use, to whom should that remark be directed?

**Comment by robdimsdale** [comment]
In order to use a Cloud Foundry buildpack, you must also be using a stack. Assuming that you are using this buildpack from within a Cloud Foundry installation, whomever manages that Cloud Foundry installation is responsible for keeping the stack up to date. You can check the info for installed stacks on a given installation with the CF CLI command: `cf stacks`.

If you think any packages in the stack are out of date, you would probably want to start by talking to the operator of the Cloud Foundry installation to see what versions of stacks they have uploaded. If the stack is out of date, they need to upload new stacks. If the available stacks are up to date but your app is using an older stack, you will need to `cf restage` your app.

If the stack is up to date in the Cloud Foundry installation and your app is using the latest available stack, and you still observe outdated packages from within your app, please let us know.

**Comment by vanschelven** [comment]
Thanks, that does indeed clear up. As I see it now, it's not the local (to me) stack that is out of date (for some definition of "out of date") but the global one: https://github.com/cloudfoundry/cflinuxfs3-release/blob/72818be6b49427e6dbbd8a439d6841001e1dd00c/manifests/manifest.yml#L93 points to Ubuntu 18.04

The definition of "out of date" that I'm using here is the one I alluded to in the original issue-description: if at some point many wheels start to become provided in a more recent manylinux version than the CF buildpack is able to support, vendoring for Python Buildpacks will become much more of a hassle.

**Comment by robdimsdale** [comment]
Ok, there's a couple more things.

Firstly, what you linked to was the **stemcell** version, not the **stack** version. In the link you pointed to, they happen to be the same version of Ubuntu, but there is an important distinction. The stemcell is the base image for the virtual machine for Cloud Foundry components, and the stack is the base image for applications. In order to upload a stack to Cloud Foundry, it is distributed as a BOSH release, and all BOSH releases must declare their stemcell compatibility. In general I believe that the stack version must be the same as the operating system version, but I'm not 100% confident that is the case.

Secondly, there are multiple lines (or major versions) of stacks - in Cloud Foundry these are `cflinuxfs2`, `cflinuxfs3` `cflinuxfs4` - and each of these corresponds to a version of Ubuntu (Xenial, Bionic, Jammy, respectively). The versions of packages in these stacks is effectively dictated by Canonical (who produce Ubuntu). Therefore, when you look at `cflinuxfs3` you're looking at Ubuntu 18.04 (Bionic). If you look at `cflinuxfs4` you're looking at Ubuntu 22.04 (Jammy).

If you compare the packages on cflinuxfs3 and on cflinuxfs4 you will see substantial changes: many packages are upgraded and some packages are added/removed/replaced altogether. An example is `libssl` - on Bionic this is `libssl1` and on Jammy this is `libssl3`. Again, the stacks are mirroring the packages in the upstream Ubuntu distributions.

To make a meaningful assessment of whether a package is up to date, you need to look at versions _for that stack_. A package like `libssl3` does not exist on Ubuntu 18.04 and hence will never exist on cflinuxfs3 - instead you would want to be looking at versions of `libssl1`.

Finally, as an aside, cflinuxfs3 will go out of support in March 2023. This is because the upstream Ubuntu 18.04 (Bionic) distribution goes out of support at this time. You may want to ask your Cloud Foundry operator to start uploading the cflinuxfs4 stack (e.g. using [this BOSH release](https://github.com/cloudfoundry/cflinuxfs4-release)) to your Cloud Foundry installation soon. Once cflinuxfs3 is out of support, cflinuxfs4 will be the only supported stack. Supporting the cflinuxfs4 stack across all buildpacks is an active track of work for the CF Buildpacks team, and is expected to be completed in the coming weeks/months.

**Comment by vanschelven** [comment]
With the information above I'm able to proceed to tackle the relevant issues... perhaps the same will hold for future visitors of this page. Anyway, closing the issue.
