### ISSUE TITLE
Vendor a single requirement without requiring all dependencies to be vendored

### ISSUE THREAD

**Issue by j12y** [cloudfoundry/python-buildpack#81]
_What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`_?

- "api_version": "2.62.0",
- cf version 6.28.0+9e024bdbd.2017-06-27

_What version of the buildpack you are using?_

Various, but reproduced in latest version v1.5.20.

_If you were attempting to accomplish a task, what was it you were attempting to do?_

I have a module in an internal enterprise github repository not published to PyPI.  I want to vendor only this development version dependency with my `cf push` as though it were a full module but without doing a `pip download` of every other dependency.

_What did you expect to happen?_

Expected to be able to include as single mylibrary-x.y.z.tar.gz in vendor/ folder.

_What was the actual behavior?_

Build fails for missing dependencies because of use of vendor/ folder expecting no internet connectivity, so would need to do a `pip download -r requirements.txt -d vendor --no-binary ...` and figure out what's needed through some trial and error.

_Please confirm where necessary_:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

If helpful I can do this, but hope either a) somebody already solved for this and I will learn something new soon as a better way or b) my description is clear and others think it's such a great idea or have had this problem too that they will rush to implement for the next bversion (or let me know a PR is welcome and I'll take a stab at it after following contribution guidelines).

**Comment by sclevine** [comment]
As far as I know, the buildpack doesn't provide this functionality.

@dgodd Would a PR for this make sense? Would this break anything to your knowledge?

**Comment by dgodd** [comment]
@sclevine @j12y At the moment the buildpack intentionally uses the inclusion of a vendor directory to switch to offline mode, and not attempt to use the internet at all. 

I believe that pip can use files on disk by referencing them as a file. Thus if `secret.whl` were in a directory called `downloads` instead of `vendor` your requirements text could look like

```
Flask==0.10.1
./downloads/secret.whl
```

Does that solve your problem?

**Comment by j12y** [comment]
Yes, thanks, I think that is a very reasonable solution.

Perhaps that use case doesn't come up very often.  It seemed if there was no internet connectivity from a connection refused or library not found, that would indicate offline mode and the `vendor` directory would be checked as a second resource.  If `vendor` existing at all is a switch to offline mode then it does work as intended.

**Comment by sclevine** [comment]
Thanks @dgodd!

> It seemed if there was no internet connectivity from a connection refused or library not found, that would indicate offline mode and the `vendor` directory would be checked as a second resource. If `vendor` existing at all is a switch to offline mode then it does work as intended.

All of the core Cloud Foundry buildpacks are designed to work fully offline, with no outbound connections, when an app is vendored. This is because many foundations run by security-conscious users don't permit internet access in staging containers. When apps are vendored incorrectly, we consider failing staging to be the safest option.
