### ISSUE TITLE
Pip install does not fully respect index-url specified in requirements.txt 

### ISSUE THREAD

**Issue by j-kaplan** [cloudfoundry/python-buildpack#86]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
"min_cli_version": "6.23.0",
"min_recommended_cli_version": "6.23.0",
"api_version": "2.82.0",

cf version 6.26.0+9c9a261fd.2017-04-06
```

What version of the buildpack you are using?
1.5.20

If you were attempting to accomplish a task, what was it you were attempting to do?
Install dependencies from requirements.txt using a custom index-url. 

What did you expect to happen?
All packages listed in requirements.txt and their dependencies get downloaded from the index-url specified in the `requirements.txt`

What was the actual behavior?
Currently the dependencies listed in the requirements.txt get installed from the custom URL, but easy_install/distutils used for installing transitive dependencies does not respect the configuration option from pip. See: https://github.com/pypa/pip/issues/2072#issuecomment-57599497

At the suggestion of @sclevine I was able to get around this issue by creating a bin/pre_compile script to create the file: `/home/vcap/.pydistutils.cfg` which specified the custom index-url as suggested by the linked github issue comment above. It would be a really nice feature to have the buildpack detect `--index-url` and `--extra-index-url` arguments listed in the `requirements.txt` and create the above configuration file for the user.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Great to hear that the workaround helped! I'll prioritize this soon.

**Comment by ewmiller** [comment]
@j-kaplan I'm having almost the exact same issue. Would you mind elaborating on what you did for the bin/pre_compile script, or pointing me towards some documentation for that feature? Thanks!

**Comment by sclevine** [comment]
@ewmiller @mguarascio @j-kaplan We would like to permanently add this functionality to the buildpack, so that it would just work. However, @dgodd has been unable to reproduce the failure. Could any of you provide a sample app that fails to stage?

Also, the manual workaround is described [here](https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1507234340000386).

**Comment by mguarascio** [comment]
Try this: https://github.com/mguarascio/python-buildpack-test. I vendored the dependencies and jsonschema tries to add vcversioner via easy_install. 

I also have a pre_compile script in there which worked for us when we specifically added the transitive dependency, but it's commented out.

**Comment by dgodd** [comment]
@mguarascio Thanks for the example, unfortunately it works for me. I made one change to choose python 3.6.4, and have attached the output. If you can shed light on why I receive a different outcome to you?

[cf_push.log.txt](https://github.com/cloudfoundry/python-buildpack/files/1657194/cf_push.log.txt)

**Comment by ewmiller** [comment]
@dgodd is the deployment environment you're pushing to connected to the internet? If so, there won't be a problem - it will pull down the extra dependencies via `easy_install` in the background and you won't notice. This line: 

```Running setup.py install for jsonschema: finished with status 'done'```

... would instead look like this: 

```Saved ./vendor/jsonschema-2.6.0.tar.gz
Complete output from command python setup.py egg_info:
Download error on https://pypi.python.org/simple/vcversioner/: [Errno 101] Network is unreachable -- Some packages may not be found!
```

The issue only occurs when trying to vendor dependencies and push to deployment environments that can't reach PyPi.

**Comment by dgodd** [comment]
Thanks @ewmiller , I had forgotten the original context of this

**Comment by einarbmag** [comment]
Hi, I am affected by this issue, here is the story:

I am pushing to an on-premise cf that only has access to a private pypi repo (mirroring the public one) , for which it needs credentials. So far, we've been using the bin/pre_compile approach and a cf service containing the credentials to create pip.conf and pydistutils.cfg files. This worked with python buildpack version 1.5.24. Now, our buildpack got updated to 1.6.6 and now I'm getting an error that the buildpack can't install pip and fails. I've confirmed that this is due to the configuration files created by pre_compile.

Any ideas why this is happening? I am unable to use the vendoring approach due to the above issue with extra easy_install dependencies. Putting the credentials in requirements.txt also fails obviously.

I thought about pushing a venv instead of vendor folder... Is there a way to do that?

**Comment by jfeeny** [comment]
Hi @einarbmag, thanks for that info. Can you provide a sample app that fails when pushing and using v1.6.6 of the buildpack? That will help us debug this.

> I've confirmed that this is due to the configuration files created by pre_compile.

Could you please elaborate on the above statement a bit? What narrows it down to pre_compile for you? If you have any logs that helped you determine this, that would also be helpful.

> I thought about pushing a venv instead of vendor folder... Is there a way to do that?

I don't believe this is possible (@sclevine, can you confirm?)

**Comment by RyanKramer** [comment]
I am having the same issue and when I tried completing the steps above it still did not work for me. Basically just copied this to my /bin/pre_compile -

`!/bin/bash

# uncomment to configure easy_install to source dependencies from ../vendor instead of pypi

echo "[easy_install]
allow_hosts = ''
find_links = $( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )/../vendor/
" > ~/.pydistutils.cfg

cat ~/.pydistutils.cfg`

but I am getting this error - 

```
 -------> Buildpack version 1.5.24
-----> Running pre-compile hook
bin/pre_compile: line 1: /bin/bash
: No such file or directory
bin/pre_compile: line 2: $'\r': command not found
bin/pre_compile: line 4: $'\r': command not found
bin/pre_compile: line 9: $'\r': command not found
allow_hosts = ''
find_links = /tmp/app/bin/../vendor/
[easy_install]
-----> Installing python-3.6.1
```

Any idea what I am doing wrong here @mguarascio ?

**Comment by punkadiddle** [comment]
@einarbmag: easy_install is used in the "bootstrap" phase early when running setup.py and it's configured separately and differnt from pip and pipenv in a distutils.cfg in a system path as seen above. Makes for three repo-location configurations at the same time.
@RyanKramer: it's a windows editor issue, bash expects newline only
